name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    uses: durgavinayb/githubWorkflows/.github/workflows/maven.yml@main
